version: '3.9'

services:
  query-service:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo:27017/iotdb
      - MONGO_COLLECTION=sensor_data
    ports:
      - "3000:3000"
    networks:
      - ingestion-network

networks:
  ingestion-network:
    external: true
